### ISSUE TITLE
bulloak check --fix doesn’t apply forge fmt settings from foundry.toml

### ISSUE THREAD

**Issue by matmilbury** [alexfertel/bulloak#53]
Given the following foundry.toml:

```toml
[fmt]
bracket_spacing = true
```

running

```sh
bulloak check test/Foo.tree --fix
```

reformats the entire `test/Foo.t.sol` file because it doesn’t apply custom `fmt` settings from `foundry.toml`.
